kind: Service
apiVersion: v1
metadata:
  name: blazorapp
  labels:
    app: blazor
spec:
  selector:
    app: blazor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazorapp
  labels:
    app: blazor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor
  template:
    metadata:
      labels:
        app: blazor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "blazorapp"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
        dapr.io/config: "tracing"
        dapr.io/log-as-json: "true"
    spec:
      containers:
      - name: blazor
        image: patobelardo/v2frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
